global using DiscountCodesGenerator.Behaviors;
global using DiscountCodesGenerator.Configuration;
global using DiscountCodesGenerator.Entities;
global using FluentValidation;
global using Grpc.Core;
global using Mapster;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using NanoidDotNet;